package com.mycompany.hastaneotomasyonu;

import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Eren Koçkan
 */
public class LoginFrm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrm
     */

    public LoginFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        lbl_email = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_loginEmail = new javax.swing.JTextField();
        txt_loginSifre = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        chechBox_showPassword = new javax.swing.JCheckBox();
        lbl_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 10, 10, 10);

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(51, 51, 51));
        lbl_email.setText("E-mail:");
        gbc.gridx = 0;
        gbc.gridy = 1;
        jPanel1.add(lbl_email, gbc);

        lbl_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(51, 51, 51));
        lbl_password.setText("Password:");
        gbc.gridx = 0;
        gbc.gridy = 2;
        jPanel1.add(lbl_password, gbc);

        txt_loginEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_loginEmail.setForeground(new java.awt.Color(51, 51, 51));
        txt_loginEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txt_loginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginEmailActionPerformed(evt);
            }
        });
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        jPanel1.add(txt_loginEmail, gbc);

        txt_loginSifre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_loginSifre.setForeground(new java.awt.Color(51, 51, 51));
        txt_loginSifre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        jPanel1.add(txt_loginSifre, gbc);

        btn_login.setBackground(new java.awt.Color(51, 153, 255));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorderPainted(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        jPanel1.add(btn_login, gbc);

        btn_exit.setBackground(new java.awt.Color(255, 51, 51));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("Exit");
        btn_exit.setBorderPainted(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        jPanel1.add(btn_exit, gbc);

        chechBox_showPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chechBox_showPassword.setForeground(new java.awt.Color(51, 51, 51));
        chechBox_showPassword.setText("Show Password");
        chechBox_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chechBox_sifreGosterActionPerformed(evt);
            }
        });
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        jPanel1.add(chechBox_showPassword, gbc);

        lbl_logo.setIcon(new ImageIcon("src/main/java/img/Mainlogo.png")); // NOI18N
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        jPanel1.add(lbl_logo, gbc);

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(51, 51, 51));
        lbl_title.setText("Hospital Management System");
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        jPanel1.add(lbl_title, gbc);

        getContentPane().add(jPanel1, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }

    private void txt_loginEmailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {
        // Kullanıcının girdiği email ve şifreyi al
        String email = txt_loginEmail.getText();
        String sifre = txt_loginSifre.getText();

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Geçersiz e-mail formatı!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User kullanici = HospitalDB.login(email, sifre); // HospitalDB sınıfından Login metodunu kullanarak kullanıcıyı kontrol et
        if (kullanici != null) { // Kullanıcı varsa
            JOptionPane.showMessageDialog(null, "Giriş Yapıldı", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            if (kullanici.user_type.compareTo("Admin") == 0) {
                AdminFrm admin = new AdminFrm();
                admin.setVisible(true);
            } else {
                AppointmentCreation randevu = new AppointmentCreation();
                randevu.setVisible(true);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Email ya da şifre hatalı!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }

    public static boolean isValidEmail(String email) {
        String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern pattern = Pattern.compile(emailPattern);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {
       Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }

    private void chechBox_sifreGosterActionPerformed(java.awt.event.ActionEvent evt) {
        if (chechBox_showPassword.isSelected()) {
            txt_loginSifre.setEchoChar((char) 0); // şifreyi göster
        } else {
            txt_loginSifre.setEchoChar('*'); // şifreyi gizle
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox chechBox_showPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_loginEmail;
    private javax.swing.JPasswordField txt_loginSifre;
    // End of variables declaration
}
